import fs from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { DocumentSchema, type DocumentPayload } from "@workspace/persistence/editorContent";
import {
  CREATE_DOCUMENT_CLI_HELP,
  createDocumentPayload,
  createDocumentPayloadFromCliArgs,
} from "./createDocumentPayload";
import {
  connectToEditor,
  type ConnectionOverrides,
} from "@workspace/sync/ClientConnection";

const SEND_DOCUMENT_HELP = `Usage: npx tsx app/wstools/sendDocument.ts [payload.json] [options]\n\n` +
  `Provide a JSON file path, or compose a payload inline with the same flags as createDocumentPayload:\n\n` +
  CREATE_DOCUMENT_CLI_HELP;

async function loadPayloadFromFile(path: string): Promise<DocumentPayload> {
  const raw = await fs.readFile(path, "utf8");
  const json = JSON.parse(raw);
  return DocumentSchema.parse(json);
}

async function resolvePayload(argv: string[]): Promise<{ payload?: DocumentPayload; exitEarly?: boolean }> {
  if (argv.length === 0) {
    return {
      payload: createDocumentPayload({
        heading: "Sample Document",
        paragraphs: [
          "This payload was generated by createDocumentPayload().",
          "Provide a JSON file path or inline options to send custom content.",
        ],
      }),
    };
  }

  const firstArg = argv[0];
  const isOption = firstArg.startsWith("-");

  if (!isOption) {
    if (argv.length > 1) {
      throw new Error("Provide either a JSON file path or inline options, not both.");
    }
    return {
      payload: await loadPayloadFromFile(firstArg),
    };
  }

  const { payload, helpRequested, outputPath } = createDocumentPayloadFromCliArgs(argv);

  if (helpRequested) {
    process.stdout.write(SEND_DOCUMENT_HELP);
    return { exitEarly: true };
  }

  if (outputPath) {
    throw new Error("--output is not supported when sending directly. Run createDocumentPayload.ts to write files.");
  }

  if (!payload) {
    throw new Error("Failed to build document payload from provided arguments");
  }

  return { payload };
}

export type SendDocumentOptions = {
  payload: DocumentPayload;
} & ConnectionOverrides;

/**
 * @deprecated Use manageDocument.ts instead for granular diff-based updates.
 * This tool continues to use 'editor:replace_document' which overwrites 
 * the entire document state and breaks selective checkpoint restores.
 */
export async function sendDocumentMessage({ payload, ...overrides }: SendDocumentOptions) {
  console.warn("[DEPRECATED] sendDocumentMessage called. Use executeWriteDocument from manageDocument.ts for granular sync.");
  const instanceId = overrides.instanceId || "default";
  const client = await connectToEditor(instanceId, overrides);
  const clientId = client.getClientId();

  try {
    await client.send({
        type: 'editor:replace_document',
        payload
    });
  } finally {
    client.disconnect();
  }

  return { instanceId, clientId };
}

async function main() {
  const argv = process.argv.slice(2);
  const { payload, exitEarly } = await resolvePayload(argv);

  if (exitEarly) {
    return;
  }

  if (!payload) {
    throw new Error("No payload available to send");
  }

  await sendDocumentMessage({ payload });
}

if (fileURLToPath(import.meta.url) === process.argv[1]) {
  main().catch((err) => {
    console.error("Failed to send document:", err);
    process.exitCode = 1;
  });
}
